title = 'Feuerwehr Kronshagen'
defaultContentLanguage = 'de'


[[menus.main]]
name = 'Startseite'
pageRef = '/'
weight = 1

#[[menus.main]]
#name = 'Posts'
#pageRef = '/posts'
#weight = 2
#
#[[menus.main]]
#name = 'Tags'
#pageRef = '/tags'
#weight = 3


[[menus.footer]]
name = 'Impressum'
pageRef = 'impressum'
weight = 4

[[menus.footer]]
name = 'Barrierefreiheit'
pageRef = 'accessibility'
weight = 5

[[menus.footer]]
name = 'Datenschutz'
pageRef = 'privacy'
weight = 6
