---
- name: Delete feature deployment for given branch
  hosts: all
  become: true
  tasks:
    - name: Remove feature deployment directory
      when: deleted_branch is defined and deleted_branch != "main"
      ansible.builtin.file:
        path: "/var/www/features/{{ deleted_branch }}"
        state: absent
