---
- name: Install and activate Fail2Ban
  hosts: all
  become: true
  handlers:
    - name: Restart_fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
  tasks:
    - name: Install Fail2Ban
      ansible.builtin.package:
        name: fail2ban
        state: present
    - name: Copy jail.local
      ansible.builtin.copy:
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 5
          allowipv6 = false

          [sshd]
          enabled = true
          backend = systemd
        dest: /etc/fail2ban/jail.local
        mode: '0755'
      notify: Restart_fail2ban
    - name: Ensure Fail2Ban is enabled and running (systemd)
      ansible.builtin.systemd:
        name: fail2ban
        enabled: true
        state: started
