---
- name: "Install and activate Fail2Ban"
  hosts: all
  become: true
  handlers:
    - name: Restart_fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
  tasks:
    - name: "Install Fail2Ban"
      ansible.builtin.package:
        name: fail2ban
        state: present
    - name: "Copy jail.local"
      ansible.builtin.copy:
        src: fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        mode: '0644'
      notify: Restart_fail2ban
    - name: "Ensure Fail2Ban is enabled and running"
      ansible.builtin.service:
        name: fail2ban
        enabled: true
        state: started
      register: fail2ban_status
      changed_when: >
        fail2ban_status.status.ActiveState is defined
        and fail2ban_status.status.ActiveState != "active"
