- name: "certificates-vserver"
  hosts: vserver
  become: yes
  vars:
    ssl_dir: /etc/letsencrypt/live/feuerwehr-kronshagen.de
    cert_file: "{{ ssl_dir }}/localhost.crt"
    key_file: "{{ ssl_dir }}/localhost.key"
  tasks:
    - name: Install certbot
      apt:
        name: certbot
        state: present
        update_cache: yes
    - name: Install Certbot Nginx plugin (Debian/Ubuntu)
      become: true
      apt:
        name: python3-certbot-nginx
        state: present
        update_cache: yes
    - name: Obtain certificate using the nginx plugin
      become: true
      command: >
        certbot --nginx
        --non-interactive
        --agree-tos
        --email homepage@feuerwehr-kronshagen.de
        -d feuerwehr-kronshagen.de
        -d test.feuerwehr-kronshagen.de
      register: certbot_output
      changed_when: "'Congratulations!' in certbot_output.stdout"
    - name: Test automatic certificate renewal
      command: certbot renew --dry-run
      register: renew_test
      changed_when: "false"
    - name: Ensure auto-renew cron job is present
      cron:
        name: "Auto-renew Let's Encrypt certs"
        job: "certbot renew --quiet --nginx && systemctl reload nginx"
        minute: 0
        hour: 3

- name: "certificates-local"
  hosts: local
  become: yes
  vars:
    ssl_dir: /etc/letsencrypt/live/localhost
    cert_file: "{{ ssl_dir }}/localhost.crt"
    key_file: "{{ ssl_dir }}/localhost.key"
  tasks:
    - name: Ensure SSL directory exists
      file:
        path: "{{ ssl_dir }}"
        state: directory
        mode: '644'
    - name: Generate self-signed certificate
      command: >
        openssl req
        -x509
        -newkey rsa:4096
        -sha512
        -nodes
        -keyout {{ key_file }}
        -out {{ cert_file }}
        -subj "/CN=localhost"
      args:
        creates: "{{ cert_file }}"
