- name: "certificates"
  hosts: none
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3-certbot
          - python3-pip
        state: present
        update_cache: yes
    - name: Obtain wildcard certificate using Certbot
      command: >
        certbot certonly
        --dns-cloudflare
        --dns-cloudflare-credentials /root/.cloudflare.ini
        --non-interactive
        --agree-tos
        --email {{ letsencrypt_email }}
        -d "{{ domain }}"
        -d "*.{{ domain }}"
      args:
        creates: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
    - name: Create Nginx config for subdomains
      template:
        src: nginx_subdomain.conf.j2
        dest: "/etc/nginx/sites-available/{{ item.subdomain }}"
      loop: "{{ subdomains }}"
    - name: Enable Nginx sites
      file:
        src: "/etc/nginx/sites-available/{{ item.subdomain }}"
        dest: "/etc/nginx/sites-enabled/{{ item.subdomain }}"
        state: link
        force: yes
      loop: "{{ subdomains }}"
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
    - name: Copy local certs
      ansible.posix.synchronize:
        src: certs/
        dest: /etc/letsencrypt/live/localhost/
        delete: true
        recursive: true
        rsync_path: "rsync"
        rsync_opts:
          - "--chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r"

- name: "certificates-local"
  hosts: local
  become: yes
  vars:
    ssl_dir: /etc/letsencrypt/live/localhost
    cert_file: "{{ ssl_dir }}/localhost.crt"
    key_file: "{{ ssl_dir }}/localhost.key"
  tasks:
    - name: Ensure SSL directory exists
      file:
        path: "{{ ssl_dir }}"
        state: directory
        mode: '644'
    - name: Generate self-signed certificate
      command: >
        openssl req
        -x509
        -newkey rsa:4096
        -sha512
        -nodes
        -keyout {{ key_file }}
        -out {{ cert_file }}
        -subj "/CN=localhost"
      args:
        creates: "{{ cert_file }}"
