---
all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    local:
      hosts:
        localDocker:
          ansible_host: localhost
          ansible_port: 2222
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    vserver:
      hosts:
        production:
          ansible_host: localhost
          ansible_port: 2222
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
