name: cleanup-test

on:
  delete:
    branches-ignore:
      - "main"

jobs:
  cleanup-test:
    runs-on: ubuntu-latest
    if: github.event.ref != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint \
          && ansible-galaxy collection install -r requirements.yml
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.VSERVER_SSHKEY }}" > ~/.ssh/id_ed25519
          sudo chmod 600  ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VSERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Create Ansible vars file
        run: |
          echo "${{ secrets.VSERVER_SUDO_PASSWORD }}" > ~/.ssh/password.txt
      - name: Ansible deployment
        run: |
          ansible-playbook \
          -i "${{ secrets.VSERVER_HOST }}," \
          --become-password-file ~/.ssh/password.txt \
          --user "${{ secrets.VSERVER_SSHUSER }}" \
          --private-key ~/.ssh/id_ed25519 \
          ansible/cleanup/*.yml
      - name: Cleanup sensitive files
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519*
          rm -f ~/.ssh/password.txt
