name: Build and Deploy SvelteKit App

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Check SvelteKit app
        run: npm run check  
      - name: Build SvelteKit app
        run: npm run build -- --base="${{github.head_ref}}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: build

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run test

  deploy-test:
    runs-on: ubuntu-latest
    environment:
      name: test-${{github.head_ref}}
      url: https://test.feuerwehr-kronshagen.de/${{github.head_ref}}
    needs: build
    steps:
      - name: install lftp
        run: sudo apt-get install lftp -y
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts
      - name: Deploy to test environment
        run: lftp -u '${{secrets.SFTP_USERNAME}},${{secrets.SFTP_PASSWORD}}' -p 22 -e "set sftp:auto-confirm yes ; set net:max-retries 1 ; mirror -e -R -p . ${{github.head_ref}} ; quit" ${{secrets.SFTP_URL}}
