name: vserver
on:
  workflow_run:
    workflows: [ "build-hugo-prod" ]
    types:
      - completed
    branches: [ "main" ]

jobs:
  ansible-deployment-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint \
          && ansible-galaxy collection install -r ansible/requirements.yml
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-prod-site
          path: ./public
      - name: Ansible deployment
        run: make 31-ansible-vserver-prod
