name: delete test deployment

on:
  delete:
    branches:
      - '**'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.ref != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: make 81-dev-dependencies-ubuntu
      - name: Ansible delete test deployment
        run: make 31-delete-vserver-test
