name: vserver-test
on:
  workflow_run:
    workflows: [ "build-hugo-test" ]
    types:
      - completed
    branches-ignore:
      - "main"

jobs:
  vserver-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint \
          && ansible-galaxy collection install -r ansible/requirements.yml
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-test-site
          path: ./public
      - name: Ansible deployment
        run: make 21-ansible-vserver-test
